language: node_js

os:
  - windows
  - linux

matrix:
## An ENOMEM error occurs with 10+ under Travis-CI for Windows.
## Disable until we can determine the cause.
#  include:
#    - os: windows
#      node_js: "latest"
  exclude:
    - os: windows
      node_js: "node"
    - os: windows
      node_js: 10

node_js:
  - "node"
  - 10
  - 8
  - 6
  - 4

branches:
  only:
  - master

after_success: npm run coveralls